wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.13
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1752410536.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 23
      - 61
      4: 3.11.13
      5: 0.16.6
      6: 4.39.3
      8:
      - 5
      13: linux-x86_64
