_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
            "3":
                - 2
                - 13
                - 55
                - 61
            "4": 3.8.8
            "5": 0.20.1
            "6": 4.46.3
            "12": 0.20.1
            "13": linux-x86_64
